brew "autoconf"
brew "automake"
brew "berkeley-db@4"
brew "boost@1.57", link: true
brew "git"
brew "libevent"
brew "libtool"
brew "miniupnpc"
brew "openssl"
brew "pkg-config"
brew "protobuf"
brew "qt"
brew "zeromq"
brew "librsvg"
